platform:
  - x86

environment:
  global:
    FORK_USER: ocaml
    FORK_BRANCH: master
    CYG_ROOT: C:\cygwin64
    PINS: "vpnkit:."
    PACKAGE: "vpnkit"
    OPAM_SWITCH: 4.08.0+mingw64c
    CYG_MIRROR: https://mirrors.kernel.org/sourceware/cygwin/

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/$env:FORK_USER/ocaml-ci-scripts/$env:FORK_BRANCH/appveyor-install.ps1"))

build_script:
  - call %CYG_ROOT%\bin\bash.exe -l -x %APPVEYOR_BUILD_FOLDER%\appveyor-opam.sh
  - call %CYG_ROOT%\bin\bash.exe -l -x %APPVEYOR_BUILD_FOLDER%\scripts\appveyor.sh

artifacts:
  - path: "./_build/default/vpnkit.exe"
  - path: "./_build/default/deps.csv"
  - path: "./_build/default/licenses.json"
  - path: "./_build/default/COMMIT"