FROM ocaml/opam:alpine-ocaml-5.3 AS build
RUN opam update
# Static zstd is needed because OCaml 5.x compiler-libs link against zstd and
# the binary is statically linked (see src/bin/config/discover.ml).
RUN sudo apk add --no-cache zstd-static

ADD . /home/opam/vpnkit
RUN sudo chown opam:opam -R vpnkit
WORKDIR /home/opam/vpnkit
RUN opam pin add vpnkit /home/opam/vpnkit --kind=path -n

RUN opam install vpnkit -y -t

# unit tests & integration tests
RUN opam exec -- dune build @runtest @e2e

# we're not interested in the intermediate artifacts
FROM scratch
COPY --from=build /home/opam/vpnkit/_build/trace.csexp /
