version: 2
jobs:
  build:
    macos:
      xcode: "12.0"
    environment:
      OPAMYES: "1"
      OPAMJOBS: "2"
      MACOSX_DEPLOYMENT_TARGET: "10.10"
      CUSTOM_OPAM: "1"
      OPAM_REPO: repo/darwin
      OPAM_COMP: "4.07.0"
      OPAMVERBOSE: 1
      TERM: vt100
    steps:
      - checkout
      - run: brew install wget
      - run: brew install pkg-config
      - run: brew install dylibbundler
      - run: brew install opam
      # Build the OCaml compiler
      - restore_cache:
           key: ocaml-cache
      - run: make -f Makefile.darwin ocaml
      - save_cache:
           paths:
             - /Users/distiller/.opam
           key: ocaml-cache
      # Build the OCaml dependencies, make sure the cache is cleared if the dependencies change.
      - restore_cache:
           key: depends-cache-{{ checksum "vpnkit.opam" }}
      - run: make -f Makefile.darwin depends
      - save_cache:
           paths:
             - /Users/distiller/.opam
           key: depends-cache-{{ checksum "vpnkit.opam" }}
      - run: make -f Makefile.darwin build
      - run: make -f Makefile.darwin artefacts
      - store_artifacts:
          path: vpnkit.tgz
      - store_artifacts:
          path: COMMIT
      - store_artifacts:
          path: OSS-LICENSES
      - run: make -f Makefile.darwin test

workflows:
  version: 2
  build-test-vpnkit:
    jobs:
      - build
