#!/bin/bash
set -x

echo hooks/post_push: attempting to compute the tree SHA of the current directory
pwd
echo The git version is
git --version

CURDIR=$(pwd)
echo Beginning experiments
cd ..
git ls-tree HEAD && echo $?
git ls-tree HEAD go && echo $?
git ls-tree HEAD -- go && echo $?
cd go
git ls-tree HEAD && echo $?
git ls-tree HEAD ../go && echo $?
git ls-tree HEAD -- ../go && echo $?
echo Complete!

exit 1
