#!/bin/bash
set -x

echo hooks/post_push: attempting to compute the tree SHA of the current directory
pwd
CURDIR=$(pwd)
cd ..
git log | head -100
git ls-tree HEAD
git ls-tree HEAD go
git ls-tree HEAD -- go
git ls-tree HEAD go | awk '{print $3}'

HASH=$(git ls-tree HEAD -- $(basename ${CURDIR}) | awk '{print $3}')

echo Tagging "${IMAGE_NAME}" with "${DOCKER_REPO}:${HASH}"
docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:${HASH}"
docker push "${DOCKER_REPO}:${HASH}"
